# This is a basic workflow to help you get started with Actions

name: Build BASICS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-BASICS:
    name: Build BASICS
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Comentarios.c
        run: |
          cd BASICS
          gcc -c Comentarios.c
          gcc -o Comentarios.exe Comentarios.o
          ./Comentarios.exe
          
      - name: Build Estructura Basica de Un Programa
        run: |
          cd BASICS
          gcc -c EstructuraBasicaPrograma.c
          gcc -o EstructuraBasicaPrograma.out EstructuraBasicaPrograma.o
          ./EstructuraBasicaPrograma.out
          
          
