# This is a basic workflow to help you get started with Actions

name: Deploy BASICS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-BASICS:
    uses: ./.github/workflows/BASICS-Build.yml
  build-IO:
    uses: ./.github/workflows/IO-Build.yml
  build-EJERCICIOS:
    uses: ./.github/workflows/EJERCICIOS-Build.yml
  build-POINTERS:
    uses: ./.github/workflows/POINTERS-Build.yml

  deploy:
    needs: [build-BASICS, build-IO, build-EJERCICIOS, build-POINTERS]
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Upload to Antares
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.ANTARES_URL }}
          remote-password: ${{ secrets.ANTARES_PWD }} 
          remote-user: ${{ secrets.ANTARES_USERNAME }}
          remote-path: "/home/illorens/CLASS/"
          sync: full
          sync-delta-excludes: |
            **/.git*
            *.md
            *.out
            *.exe
            *.o
      
